name: violence-judicial-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - tesseract
  - poppler
  - pip:
      - fastapi>=0.115.0
      - httpx>=0.27.0
      - jsonschema>=4.22.0
      - ipykernel>=6.29.0
      - jupyterlab>=4.2.0
      - langgraph>=0.2.56
      - loguru>=0.7.2
      - matplotlib>=3.9.0
      - pandas>=2.2.0
      - pymongo>=4.8.0
      - pydantic>=2.7.0
      - python-dotenv>=1.0.1
      - dnspython>=2.6.1
      - python-multipart>=0.0.9
      - rank_bm25>=0.2.2
      - seaborn>=0.13.0
      - spacy>=3.8.0
      - streamlit>=1.40.0
      - transformers>=4.46.0
      - sentencepiece>=0.2.0
      - uvicorn>=0.30.0
      - wordcloud>=1.9.3
